apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap_nodered.name }}
  namespace: {{ .Values.namespace }}

data:
  
{{- range $path, $_ := (.Files.Glob "settingsjs/*") }}
  {{ trimPrefix "settingsjs/" $path }}: |+
    {{- tpl ($.Files.Get $path) $ | nindent 4 }}
{{ end -}}